-- Create profiles table for user management
create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  display_name text,
  created_at timestamp with time zone default timezone('utc'::text, now())
);

-- Create lectures table for storing lecture recordings
create table if not exists public.lectures (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  title text not null,
  description text,
  duration_ms integer,
  audio_url text,
  transcript text,
  created_at timestamp with time zone default timezone('utc'::text, now()),
  updated_at timestamp with time zone default timezone('utc'::text, now())
);

-- Create transcriptions table for real-time transcription data
create table if not exists public.transcriptions (
  id uuid primary key default gen_random_uuid(),
  lecture_id uuid not null references public.lectures(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  raw_text text not null,
  timestamp_ms integer,
  created_at timestamp with time zone default timezone('utc'::text, now())
);

-- Create lecture notes table
create table if not exists public.lecture_notes (
  id uuid primary key default gen_random_uuid(),
  lecture_id uuid not null references public.lectures(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  content text not null,
  created_at timestamp with time zone default timezone('utc'::text, now()),
  updated_at timestamp with time zone default timezone('utc'::text, now())
);

-- Create summaries table (generated by Gemini)
create table if not exists public.summaries (
  id uuid primary key default gen_random_uuid(),
  lecture_id uuid not null references public.lectures(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  summary_text text not null,
  key_points text[], -- Array of key points
  created_at timestamp with time zone default timezone('utc'::text, now()),
  updated_at timestamp with time zone default timezone('utc'::text, now())
);

-- Create flashcards table (generated by Gemini)
create table if not exists public.flashcards (
  id uuid primary key default gen_random_uuid(),
  lecture_id uuid not null references public.lectures(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  question text not null,
  answer text not null,
  difficulty_level text default 'medium', -- easy, medium, hard
  created_at timestamp with time zone default timezone('utc'::text, now()),
  updated_at timestamp with time zone default timezone('utc'::text, now())
);

-- Create exam questions table (generated by Gemini)
create table if not exists public.exam_questions (
  id uuid primary key default gen_random_uuid(),
  lecture_id uuid not null references public.lectures(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  question_text text not null,
  option_a text not null,
  option_b text not null,
  option_c text not null,
  option_d text not null,
  correct_answer text not null,
  explanation text,
  created_at timestamp with time zone default timezone('utc'::text, now())
);

-- Enable RLS for all tables
alter table public.profiles enable row level security;
alter table public.lectures enable row level security;
alter table public.transcriptions enable row level security;
alter table public.lecture_notes enable row level security;
alter table public.summaries enable row level security;
alter table public.flashcards enable row level security;
alter table public.exam_questions enable row level security;

-- RLS Policies for profiles
create policy "profiles_select_own"
  on public.profiles for select
  using (auth.uid() = id);

create policy "profiles_insert_own"
  on public.profiles for insert
  with check (auth.uid() = id);

create policy "profiles_update_own"
  on public.profiles for update
  using (auth.uid() = id);

create policy "profiles_delete_own"
  on public.profiles for delete
  using (auth.uid() = id);

-- RLS Policies for lectures
create policy "lectures_select_own"
  on public.lectures for select
  using (auth.uid() = user_id);

create policy "lectures_insert_own"
  on public.lectures for insert
  with check (auth.uid() = user_id);

create policy "lectures_update_own"
  on public.lectures for update
  using (auth.uid() = user_id);

create policy "lectures_delete_own"
  on public.lectures for delete
  using (auth.uid() = user_id);

-- RLS Policies for transcriptions
create policy "transcriptions_select_own"
  on public.transcriptions for select
  using (auth.uid() = user_id);

create policy "transcriptions_insert_own"
  on public.transcriptions for insert
  with check (auth.uid() = user_id);

create policy "transcriptions_update_own"
  on public.transcriptions for update
  using (auth.uid() = user_id);

-- RLS Policies for lecture_notes
create policy "lecture_notes_select_own"
  on public.lecture_notes for select
  using (auth.uid() = user_id);

create policy "lecture_notes_insert_own"
  on public.lecture_notes for insert
  with check (auth.uid() = user_id);

create policy "lecture_notes_update_own"
  on public.lecture_notes for update
  using (auth.uid() = user_id);

create policy "lecture_notes_delete_own"
  on public.lecture_notes for delete
  using (auth.uid() = user_id);

-- RLS Policies for summaries
create policy "summaries_select_own"
  on public.summaries for select
  using (auth.uid() = user_id);

create policy "summaries_insert_own"
  on public.summaries for insert
  with check (auth.uid() = user_id);

create policy "summaries_update_own"
  on public.summaries for update
  using (auth.uid() = user_id);

-- RLS Policies for flashcards
create policy "flashcards_select_own"
  on public.flashcards for select
  using (auth.uid() = user_id);

create policy "flashcards_insert_own"
  on public.flashcards for insert
  with check (auth.uid() = user_id);

create policy "flashcards_update_own"
  on public.flashcards for update
  using (auth.uid() = user_id);

create policy "flashcards_delete_own"
  on public.flashcards for delete
  using (auth.uid() = user_id);

-- RLS Policies for exam_questions
create policy "exam_questions_select_own"
  on public.exam_questions for select
  using (auth.uid() = user_id);

create policy "exam_questions_insert_own"
  on public.exam_questions for insert
  with check (auth.uid() = user_id);

create policy "exam_questions_update_own"
  on public.exam_questions for update
  using (auth.uid() = user_id);
